server:
  port: 8091

spring:
  application:
    name: health-code
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    url: jdbc:mysql://8.138.5.230:3306/health_code_health_code?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: healthcode
    password: healthcode

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名
    # 开启日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto